### ISSUE TITLE
Using Background and foreground colors causing preview corruption 

### ISSUE THREAD

**Issue by manujchandra** [xlucn/fontpreview-ueberzug#22] opened 2024-01-30 05:49 UTC
When I call:

`fontpreview-ueberzug`

Correct preview is generated

![Screenshot_2024-01-30_11-13-35](https://github.com/xlucn/fontpreview-ueberzug/assets/15191493/620f75d0-f49d-448c-bb8e-5aaf1093fab9)

If I use background and foreground colors:

`fontpreview-ueberzug -b '#272822' -f '#f8f8f2'`

![Screenshot_2024-01-30_11-13-22](https://github.com/xlucn/fontpreview-ueberzug/assets/15191493/8d0be824-ce8f-435e-adf8-eec7d501515d)

I get the above result.

Tried in both XFCE terminal and Alacritty.

### Environment:

- ueberzugpp 2.9.2
- Debian 12 (Spiral Linux)
- Current master brach of fontpreview-ueberzug
- xonsh/0.14.4

**Comment by xlucn** [comment] 2024-01-30 07:57
Thanks for the report. I can reproduce it.

However, if you could try to open the image `/tmp/fontpreview-ueberzug-img.png` with other image viewers while running `fontpreview`, please check if it is shown with the right color.

If confirmed, the issue might be: either `fontpreview` generates the image in a somehow weird format, or ueberzugpp parses that image in a somehow weird way. Something is not done by the standard. I will look further into it.

**Comment by xlucn** [comment] 2024-01-30 09:17
Okay, I found that currently `ueberzugpp` 2.9.2 can't display most of the png images `fontpreview` generates. As a workaround, I have moved from png to jpeg format, which I tested without issues. You can try that with the latest master branch.

**Comment by manujchandra** [comment] 2024-01-30 10:31
Just for the sake of completion, I can view /tmp/fontpreview-ueberzug-img.png properly on sxiv

![Screenshot_2024-01-30_15-52-03](https://github.com/xlucn/fontpreview-ueberzug/assets/15191493/1540244a-6f73-4253-828d-e11855d963cd)

Thanks for such a prompt reply. Let me try the master branch. 🙏🏽

EDIT : I have tried the new master branch and it seems to be working fine!

**Comment by xlucn** [comment] 2024-01-31 11:56
I think the reason is that `fontpreview` was somehow generating images with 16-bit color depth, and `ueberzugpp` can't deal with that. If interested, see the mentioning issue above this comment.

So, I think my workaround is fine. I could also generate png images in 8-bit color depth (already tested), but there seems no need for the change.

As for this issue, I am closing it now since the problem is not at my end anymore.

**Closed by xlucn** 2024-01-31 11:56 UTC
